// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connected_account.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const upsertConnectedAccount = `-- name: UpsertConnectedAccount :one
INSERT INTO connected_accounts (
    user_id,
    provider,
    provider_user_id,
    email,
    access_token,
    refresh_token,
    expires_at,
    scopes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, provider)
DO UPDATE SET
    provider_user_id = EXCLUDED.provider_user_id,
    email = EXCLUDED.email,
    access_token = EXCLUDED.access_token,
    refresh_token = COALESCE(EXCLUDED.refresh_token, connected_accounts.refresh_token),
    expires_at = EXCLUDED.expires_at,
    scopes = EXCLUDED.scopes,
    updated_at = now()
RETURNING id, user_id, provider, provider_user_id, email, access_token, refresh_token, expires_at, scopes, created_at, updated_at
`

type UpsertConnectedAccountParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID sql.NullString
	Email          sql.NullString
	AccessToken    string
	RefreshToken   sql.NullString
	ExpiresAt      sql.NullTime
	Scopes         sql.NullString
}

func (q *Queries) UpsertConnectedAccount(ctx context.Context, arg UpsertConnectedAccountParams) (ConnectedAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertConnectedAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
