// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gemini.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserGeminiKey = `-- name: CreateUserGeminiKey :one
INSERT INTO user_gemini_keys (
    id,
    user_id,
    api_key,
    created_at,
    updated_at
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)
RETURNING id, user_id, api_key, created_at, updated_at
`

type CreateUserGeminiKeyParams struct {
	UserID uuid.UUID
	ApiKey string
}

func (q *Queries) CreateUserGeminiKey(ctx context.Context, arg CreateUserGeminiKeyParams) (UserGeminiKey, error) {
	row := q.db.QueryRowContext(ctx, createUserGeminiKey, arg.UserID, arg.ApiKey)
	var i UserGeminiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserGeminiKey = `-- name: DeleteUserGeminiKey :exec
DELETE FROM user_gemini_keys
WHERE user_id = $1
`

func (q *Queries) DeleteUserGeminiKey(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserGeminiKey, userID)
	return err
}

const getUserGeminiKeyByUserID = `-- name: GetUserGeminiKeyByUserID :one
SELECT id, user_id, api_key, created_at, updated_at
FROM user_gemini_keys
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserGeminiKeyByUserID(ctx context.Context, userID uuid.UUID) (UserGeminiKey, error) {
	row := q.db.QueryRowContext(ctx, getUserGeminiKeyByUserID, userID)
	var i UserGeminiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserGeminiKey = `-- name: UpdateUserGeminiKey :one
UPDATE user_gemini_keys
SET
    api_key = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, api_key, created_at, updated_at
`

type UpdateUserGeminiKeyParams struct {
	UserID uuid.UUID
	ApiKey string
}

func (q *Queries) UpdateUserGeminiKey(ctx context.Context, arg UpdateUserGeminiKeyParams) (UserGeminiKey, error) {
	row := q.db.QueryRowContext(ctx, updateUserGeminiKey, arg.UserID, arg.ApiKey)
	var i UserGeminiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasGeminiKey = `-- name: UserHasGeminiKey :one
SELECT EXISTS (
    SELECT 1
    FROM user_gemini_keys
    WHERE user_id = $1
)
`

func (q *Queries) UserHasGeminiKey(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasGeminiKey, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
