// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ConnectedAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID sql.NullString
	Email          sql.NullString
	AccessToken    string
	RefreshToken   sql.NullString
	ExpiresAt      sql.NullTime
	Scopes         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID         uuid.UUID
	Email      string
	Password   string
	IsVerified bool
	Plan       sql.NullString
	CreatedAt  sql.NullTime
}

type WebhookTrigger struct {
	ID             uuid.UUID
	WorkflowID     uuid.UUID
	UserID         uuid.UUID
	WebhookUrlID   string
	FrontendNodeID string
	CreatedAt      sql.NullTime
}

type Workflow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	TriggerType string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkflowEdge struct {
	ID              uuid.UUID
	WorkflowID      uuid.UUID
	SourceStepID    uuid.UUID
	TargetStepID    uuid.UUID
	ConditionBranch sql.NullString
	CreatedAt       sql.NullTime
}

type WorkflowRun struct {
	ID           uuid.UUID
	WorkflowID   uuid.UUID
	UserID       uuid.UUID
	Status       string
	StartedAt    sql.NullTime
	FinishedAt   sql.NullTime
	ErrorMessage sql.NullString
	CreatedAt    time.Time
}

type WorkflowStep struct {
	ID             uuid.UUID
	WorkflowID     uuid.UUID
	FrontendNodeID string
	StepOrder      int32
	StepType       string
	Config         json.RawMessage
	CreatedAt      time.Time
}

type WorkflowStepRun struct {
	ID             uuid.UUID
	WorkflowRunID  uuid.UUID
	WorkflowStepID uuid.UUID
	Status         string
	Input          pqtype.NullRawMessage
	Output         pqtype.NullRawMessage
	ErrorMessage   sql.NullString
	StartedAt      sql.NullTime
	FinishedAt     sql.NullTime
	CreatedAt      time.Time
}
