// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type ConnectedAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID sql.NullString
	Email          sql.NullString
	AccessToken    string
	RefreshToken   sql.NullString
	ExpiresAt      sql.NullTime
	Scopes         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type User struct {
	ID         uuid.UUID
	Email      string
	Password   string
	IsVerified bool
	Plan       sql.NullString
	CreatedAt  sql.NullTime
}
