// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	Email      string
	Password   string
	IsVerified bool
	Plan       sql.NullString
	CreatedAt  sql.NullTime
}
