// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMonthlyUsage = `-- name: GetMonthlyUsage :one
SELECT id, user_id, month, workflow_runs, created_at, updated_at
FROM workflow_usage
WHERE user_id = $1 AND month = $2
`

type GetMonthlyUsageParams struct {
	UserID uuid.UUID
	Month  string
}

func (q *Queries) GetMonthlyUsage(ctx context.Context, arg GetMonthlyUsageParams) (WorkflowUsage, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyUsage, arg.UserID, arg.Month)
	var i WorkflowUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.WorkflowRuns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementWorkflowUsage = `-- name: IncrementWorkflowUsage :one
INSERT INTO workflow_usage (
    id,
    user_id,
    month,
    workflow_runs
)
VALUES (
    $1,
    $2,
    $3,
    1
)
ON CONFLICT (user_id, month)
DO UPDATE SET
    workflow_runs = workflow_usage.workflow_runs + 1,
    updated_at = NOW()
RETURNING id, user_id, month, workflow_runs, created_at, updated_at
`

type IncrementWorkflowUsageParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Month  string
}

func (q *Queries) IncrementWorkflowUsage(ctx context.Context, arg IncrementWorkflowUsageParams) (WorkflowUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementWorkflowUsage, arg.ID, arg.UserID, arg.Month)
	var i WorkflowUsage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.WorkflowRuns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
