// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createWebhookTrigger = `-- name: CreateWebhookTrigger :one
INSERT INTO webhook_triggers (
    id,
    workflow_id,
    user_id,
    webhook_url_id,
    frontend_node_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workflow_id, user_id, webhook_url_id, frontend_node_id, created_at
`

type CreateWebhookTriggerParams struct {
	ID             uuid.UUID
	WorkflowID     uuid.UUID
	UserID         uuid.UUID
	WebhookUrlID   string
	FrontendNodeID string
}

func (q *Queries) CreateWebhookTrigger(ctx context.Context, arg CreateWebhookTriggerParams) (WebhookTrigger, error) {
	row := q.db.QueryRowContext(ctx, createWebhookTrigger,
		arg.ID,
		arg.WorkflowID,
		arg.UserID,
		arg.WebhookUrlID,
		arg.FrontendNodeID,
	)
	var i WebhookTrigger
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.WebhookUrlID,
		&i.FrontendNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id, user_id, name, description, trigger_type, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, description, trigger_type, is_active, schedule_enabled, schedule_type, schedule_value, next_run_at, last_run_at, is_schedule_running, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	TriggerType string
	IsActive    bool
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.IsActive,
		&i.ScheduleEnabled,
		&i.ScheduleType,
		&i.ScheduleValue,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.IsScheduleRunning,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowEdge = `-- name: CreateWorkflowEdge :one
INSERT INTO workflow_edges (
    id,
    workflow_id,
    source_step_id,
    target_step_id,
    condition_branch
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workflow_id, source_step_id, target_step_id, condition_branch, created_at
`

type CreateWorkflowEdgeParams struct {
	ID              uuid.UUID
	WorkflowID      uuid.UUID
	SourceStepID    uuid.UUID
	TargetStepID    uuid.UUID
	ConditionBranch sql.NullString
}

func (q *Queries) CreateWorkflowEdge(ctx context.Context, arg CreateWorkflowEdgeParams) (WorkflowEdge, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowEdge,
		arg.ID,
		arg.WorkflowID,
		arg.SourceStepID,
		arg.TargetStepID,
		arg.ConditionBranch,
	)
	var i WorkflowEdge
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SourceStepID,
		&i.TargetStepID,
		&i.ConditionBranch,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id, workflow_id, user_id, status, started_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, workflow_id, user_id, status, started_at, finished_at, error_message, created_at
`

type CreateWorkflowRunParams struct {
	ID         uuid.UUID
	WorkflowID uuid.UUID
	UserID     uuid.UUID
	Status     string
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.UserID,
		arg.Status,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO workflow_steps (
    id,
    workflow_id,
    frontend_node_id,
    step_order,
    step_type,
    config,
    position_x,
    position_y
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, workflow_id, frontend_node_id, step_order, step_type, config, position_x, position_y, created_at
`

type CreateWorkflowStepParams struct {
	ID             uuid.UUID
	WorkflowID     uuid.UUID
	FrontendNodeID string
	StepOrder      int32
	StepType       string
	Config         json.RawMessage
	PositionX      float64
	PositionY      float64
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStep,
		arg.ID,
		arg.WorkflowID,
		arg.FrontendNodeID,
		arg.StepOrder,
		arg.StepType,
		arg.Config,
		arg.PositionX,
		arg.PositionY,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FrontendNodeID,
		&i.StepOrder,
		&i.StepType,
		&i.Config,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowStepRun = `-- name: CreateWorkflowStepRun :one
INSERT INTO workflow_step_runs (
    id,
    workflow_run_id,
    workflow_step_id,
    status,
    input,
    output,
    error_message,
    started_at,
    finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, workflow_run_id, workflow_step_id, status, input, output, error_message, started_at, finished_at, created_at
`

type CreateWorkflowStepRunParams struct {
	ID             uuid.UUID
	WorkflowRunID  uuid.UUID
	WorkflowStepID uuid.UUID
	Status         string
	Input          pqtype.NullRawMessage
	Output         pqtype.NullRawMessage
	ErrorMessage   sql.NullString
}

func (q *Queries) CreateWorkflowStepRun(ctx context.Context, arg CreateWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStepRun,
		arg.ID,
		arg.WorkflowRunID,
		arg.WorkflowStepID,
		arg.Status,
		arg.Input,
		arg.Output,
		arg.ErrorMessage,
	)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookTriggersByWorkflow = `-- name: DeleteWebhookTriggersByWorkflow :exec
DELETE FROM webhook_triggers
WHERE workflow_id = $1
`

func (q *Queries) DeleteWebhookTriggersByWorkflow(ctx context.Context, workflowID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookTriggersByWorkflow, workflowID)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND user_id = $2
`

type DeleteWorkflowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, arg.ID, arg.UserID)
	return err
}

const deleteWorkflowEdges = `-- name: DeleteWorkflowEdges :exec
DELETE FROM workflow_edges
WHERE workflow_id = $1
`

func (q *Queries) DeleteWorkflowEdges(ctx context.Context, workflowID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowEdges, workflowID)
	return err
}

const deleteWorkflowSteps = `-- name: DeleteWorkflowSteps :exec
DELETE FROM workflow_steps
WHERE workflow_id = $1
`

func (q *Queries) DeleteWorkflowSteps(ctx context.Context, workflowID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowSteps, workflowID)
	return err
}

const getWebhookTriggerByURLID = `-- name: GetWebhookTriggerByURLID :one
SELECT id, workflow_id, user_id, webhook_url_id, frontend_node_id, created_at FROM webhook_triggers
WHERE webhook_url_id = $1
`

func (q *Queries) GetWebhookTriggerByURLID(ctx context.Context, webhookUrlID string) (WebhookTrigger, error) {
	row := q.db.QueryRowContext(ctx, getWebhookTriggerByURLID, webhookUrlID)
	var i WebhookTrigger
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.WebhookUrlID,
		&i.FrontendNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, user_id, name, description, trigger_type, is_active, schedule_enabled, schedule_type, schedule_value, next_run_at, last_run_at, is_schedule_running, created_at, updated_at FROM workflows
WHERE id = $1 AND user_id = $2
`

type GetWorkflowByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowByID, arg.ID, arg.UserID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.IsActive,
		&i.ScheduleEnabled,
		&i.ScheduleType,
		&i.ScheduleValue,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.IsScheduleRunning,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowSchedule = `-- name: GetWorkflowSchedule :one
SELECT
    schedule_enabled,
    schedule_type,
    schedule_value,
    next_run_at,
    last_run_at
FROM workflows
WHERE id = $1 AND user_id = $2
`

type GetWorkflowScheduleParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkflowScheduleRow struct {
	ScheduleEnabled bool
	ScheduleType    sql.NullString
	ScheduleValue   sql.NullString
	NextRunAt       sql.NullTime
	LastRunAt       sql.NullTime
}

func (q *Queries) GetWorkflowSchedule(ctx context.Context, arg GetWorkflowScheduleParams) (GetWorkflowScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowSchedule, arg.ID, arg.UserID)
	var i GetWorkflowScheduleRow
	err := row.Scan(
		&i.ScheduleEnabled,
		&i.ScheduleType,
		&i.ScheduleValue,
		&i.NextRunAt,
		&i.LastRunAt,
	)
	return i, err
}

const listDueScheduledWorkflows = `-- name: ListDueScheduledWorkflows :many
SELECT id, user_id, name, description, trigger_type, is_active, schedule_enabled, schedule_type, schedule_value, next_run_at, last_run_at, is_schedule_running, created_at, updated_at
FROM workflows
WHERE schedule_enabled = true
  AND next_run_at IS NOT NULL
  AND next_run_at <= NOW()
  AND is_active = true
  AND is_schedule_running = false
  AND trigger_type = 'schedule'
`

func (q *Queries) ListDueScheduledWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.IsActive,
			&i.ScheduleEnabled,
			&i.ScheduleType,
			&i.ScheduleValue,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.IsScheduleRunning,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookTriggersByWorkflow = `-- name: ListWebhookTriggersByWorkflow :many
SELECT id, workflow_id, user_id, webhook_url_id, frontend_node_id, created_at FROM webhook_triggers
WHERE workflow_id = $1
`

func (q *Queries) ListWebhookTriggersByWorkflow(ctx context.Context, workflowID uuid.UUID) ([]WebhookTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookTriggersByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookTrigger
	for rows.Next() {
		var i WebhookTrigger
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.UserID,
			&i.WebhookUrlID,
			&i.FrontendNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowByUser = `-- name: ListWorkflowByUser :many
SELECT id, user_id, name, description, trigger_type, is_active, schedule_enabled, schedule_type, schedule_value, next_run_at, last_run_at, is_schedule_running, created_at, updated_at FROM workflows
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowByUser(ctx context.Context, userID uuid.UUID) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.IsActive,
			&i.ScheduleEnabled,
			&i.ScheduleType,
			&i.ScheduleValue,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.IsScheduleRunning,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEdges = `-- name: ListWorkflowEdges :many
SELECT
    we.id,
    we.workflow_id,
    we.source_step_id,
    we.target_step_id,
    we.condition_branch,
    we.created_at,

    source.frontend_node_id AS source_frontend_node_id,
    target.frontend_node_id AS target_frontend_node_id
FROM workflow_edges we
JOIN workflow_steps source ON source.id = we.source_step_id
JOIN workflow_steps target ON target.id = we.target_step_id
WHERE we.workflow_id = $1
ORDER BY we.created_at ASC
`

type ListWorkflowEdgesRow struct {
	ID                   uuid.UUID
	WorkflowID           uuid.UUID
	SourceStepID         uuid.UUID
	TargetStepID         uuid.UUID
	ConditionBranch      sql.NullString
	CreatedAt            sql.NullTime
	SourceFrontendNodeID string
	TargetFrontendNodeID string
}

func (q *Queries) ListWorkflowEdges(ctx context.Context, workflowID uuid.UUID) ([]ListWorkflowEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowEdges, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowEdgesRow
	for rows.Next() {
		var i ListWorkflowEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.SourceStepID,
			&i.TargetStepID,
			&i.ConditionBranch,
			&i.CreatedAt,
			&i.SourceFrontendNodeID,
			&i.TargetFrontendNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEdgesForExecution = `-- name: ListWorkflowEdgesForExecution :many
SELECT id, workflow_id, source_step_id, target_step_id, condition_branch, created_at
FROM workflow_edges
WHERE workflow_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkflowEdgesForExecution(ctx context.Context, workflowID uuid.UUID) ([]WorkflowEdge, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowEdgesForExecution, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEdge
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.SourceStepID,
			&i.TargetStepID,
			&i.ConditionBranch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, user_id, status, started_at, finished_at, error_message, created_at FROM workflow_runs
WHERE workflow_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListWorkflowRunsParams struct {
	WorkflowID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRuns, arg.WorkflowID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.UserID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepRuns = `-- name: ListWorkflowStepRuns :many
SELECT id, workflow_run_id, workflow_step_id, status, input, output, error_message, started_at, finished_at, created_at
FROM workflow_step_runs
WHERE workflow_run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkflowStepRuns(ctx context.Context, workflowRunID uuid.UUID) ([]WorkflowStepRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowStepRuns, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepRun
	for rows.Next() {
		var i WorkflowStepRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.WorkflowStepID,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT id, workflow_id, frontend_node_id, step_order, step_type, config, position_x, position_y, created_at FROM workflow_steps
WHERE workflow_id = $1
ORDER BY step_order ASC
`

func (q *Queries) ListWorkflowSteps(ctx context.Context, workflowID uuid.UUID) ([]WorkflowStep, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowSteps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStep
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.FrontendNodeID,
			&i.StepOrder,
			&i.StepType,
			&i.Config,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleRunning = `-- name: MarkScheduleRunning :exec
UPDATE workflows
SET
    is_schedule_running = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkScheduleRunningParams struct {
	ID                uuid.UUID
	IsScheduleRunning bool
}

func (q *Queries) MarkScheduleRunning(ctx context.Context, arg MarkScheduleRunningParams) error {
	_, err := q.db.ExecContext(ctx, markScheduleRunning, arg.ID, arg.IsScheduleRunning)
	return err
}

const markWorkflowScheduleRun = `-- name: MarkWorkflowScheduleRun :exec
UPDATE workflows
SET
    last_run_at = NOW(),
    next_run_at = $2,
    is_schedule_running = false,
    updated_at = NOW()
WHERE id = $1
`

type MarkWorkflowScheduleRunParams struct {
	ID        uuid.UUID
	NextRunAt sql.NullTime
}

func (q *Queries) MarkWorkflowScheduleRun(ctx context.Context, arg MarkWorkflowScheduleRunParams) error {
	_, err := q.db.ExecContext(ctx, markWorkflowScheduleRun, arg.ID, arg.NextRunAt)
	return err
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :exec
UPDATE workflow_runs
SET status = $2,
    error_message = $3,
    finished_at = NOW()
WHERE id = $1
`

type UpdateWorkflowRunStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowRunStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const updateWorkflowSchedule = `-- name: UpdateWorkflowSchedule :exec
UPDATE workflows
SET
    schedule_enabled = $2,
    schedule_type = $3,
    schedule_value = $4,
    next_run_at = $5,
    updated_at = NOW()
WHERE id = $1 AND user_id = $6
`

type UpdateWorkflowScheduleParams struct {
	ID              uuid.UUID
	ScheduleEnabled bool
	ScheduleType    sql.NullString
	ScheduleValue   sql.NullString
	NextRunAt       sql.NullTime
	UserID          uuid.UUID
}

func (q *Queries) UpdateWorkflowSchedule(ctx context.Context, arg UpdateWorkflowScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowSchedule,
		arg.ID,
		arg.ScheduleEnabled,
		arg.ScheduleType,
		arg.ScheduleValue,
		arg.NextRunAt,
		arg.UserID,
	)
	return err
}

const updateWorkflowStepRunStatus = `-- name: UpdateWorkflowStepRunStatus :exec
UPDATE workflow_step_runs
SET status = $2,
    output = $3,
    error_message = $4,
    finished_at = NOW()
WHERE id = $1
`

type UpdateWorkflowStepRunStatusParams struct {
	ID           uuid.UUID
	Status       string
	Output       pqtype.NullRawMessage
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateWorkflowStepRunStatus(ctx context.Context, arg UpdateWorkflowStepRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowStepRunStatus,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.ErrorMessage,
	)
	return err
}
