// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id, user_id, name, description, trigger_type, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, description, trigger_type, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	TriggerType string
	IsActive    bool
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id, workflow_id, user_id, status, started_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, workflow_id, user_id, status, started_at, finished_at, error_message, created_at
`

type CreateWorkflowRunParams struct {
	ID         uuid.UUID
	WorkflowID uuid.UUID
	UserID     uuid.UUID
	Status     string
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.UserID,
		arg.Status,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO workflow_steps (
    id, workflow_id, step_order, step_type, config
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workflow_id, step_order, step_type, config, created_at
`

type CreateWorkflowStepParams struct {
	ID         uuid.UUID
	WorkflowID uuid.UUID
	StepOrder  int32
	StepType   string
	Config     json.RawMessage
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStep,
		arg.ID,
		arg.WorkflowID,
		arg.StepOrder,
		arg.StepType,
		arg.Config,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.StepOrder,
		&i.StepType,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowStepRun = `-- name: CreateWorkflowStepRun :one
INSERT INTO workflow_step_runs (
    id,
    workflow_run_id,
    workflow_step_id,
    status,
    input,
    output,
    error_message,
    started_at,
    finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, workflow_run_id, workflow_step_id, status, input, output, error_message, started_at, finished_at, created_at
`

type CreateWorkflowStepRunParams struct {
	ID             uuid.UUID
	WorkflowRunID  uuid.UUID
	WorkflowStepID uuid.UUID
	Status         string
	Input          pqtype.NullRawMessage
	Output         pqtype.NullRawMessage
	ErrorMessage   sql.NullString
}

func (q *Queries) CreateWorkflowStepRun(ctx context.Context, arg CreateWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStepRun,
		arg.ID,
		arg.WorkflowRunID,
		arg.WorkflowStepID,
		arg.Status,
		arg.Input,
		arg.Output,
		arg.ErrorMessage,
	)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.WorkflowStepID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND user_id = $2
`

type DeleteWorkflowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, arg.ID, arg.UserID)
	return err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, user_id, name, description, trigger_type, is_active, created_at, updated_at FROM workflows
WHERE id = $1 AND user_id = $2
`

type GetWorkflowByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowByID, arg.ID, arg.UserID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowByUser = `-- name: ListWorkflowByUser :many
SELECT id, user_id, name, description, trigger_type, is_active, created_at, updated_at FROM workflows
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowByUser(ctx context.Context, userID uuid.UUID) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, user_id, status, started_at, finished_at, error_message, created_at FROM workflow_runs
WHERE workflow_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListWorkflowRunsParams struct {
	WorkflowID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRuns, arg.WorkflowID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.UserID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepRuns = `-- name: ListWorkflowStepRuns :many
SELECT id, workflow_run_id, workflow_step_id, status, input, output, error_message, started_at, finished_at, created_at
FROM workflow_step_runs
WHERE workflow_run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkflowStepRuns(ctx context.Context, workflowRunID uuid.UUID) ([]WorkflowStepRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowStepRuns, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepRun
	for rows.Next() {
		var i WorkflowStepRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.WorkflowStepID,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT id, workflow_id, step_order, step_type, config, created_at FROM workflow_steps
WHERE workflow_id = $1
ORDER BY step_order ASC
`

func (q *Queries) ListWorkflowSteps(ctx context.Context, workflowID uuid.UUID) ([]WorkflowStep, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowSteps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStep
	for rows.Next() {
		var i WorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepOrder,
			&i.StepType,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :exec
UPDATE workflow_runs
SET status = $2,
    error_message = $3,
    finished_at = NOW()
WHERE id = $1
`

type UpdateWorkflowRunStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowRunStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const updateWorkflowStepRunStatus = `-- name: UpdateWorkflowStepRunStatus :exec
UPDATE workflow_step_runs
SET status = $2,
    output = $3,
    error_message = $4,
    finished_at = NOW()
WHERE id = $1
`

type UpdateWorkflowStepRunStatusParams struct {
	ID           uuid.UUID
	Status       string
	Output       pqtype.NullRawMessage
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateWorkflowStepRunStatus(ctx context.Context, arg UpdateWorkflowStepRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowStepRunStatus,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.ErrorMessage,
	)
	return err
}
